In [1]:
import pandas as pd

In [2]:
# data = pd.read_csv('C:/Users/pranj/OneDrive/Desktop/spam detection/bbc_news.csv')
data = pd.read_csv('bbc_news.csv')

In [3]:
data

,title,pubDate,guid,link,description
0,Ukraine: Angry Zelensky vows to punish Russian...,"Mon, 07 Mar 2022 08:01:56 GMT",https://www.bbc.co.uk/news/world-europe-60638042,https://www.bbc.co.uk/news/world-europe-606380...,The Ukrainian president says the country will ...
1,War in Ukraine: Taking cover in a town under a...,"Sun, 06 Mar 2022 22:49:58 GMT",https://www.bbc.co.uk/news/world-europe-60641873,https://www.bbc.co.uk/news/world-europe-606418...,"Jeremy Bowen was on the frontline in Irpin, as..."
2,Ukraine war 'catastrophic for global food',"Mon, 07 Mar 2022 00:14:42 GMT",https://www.bbc.co.uk/news/business-60623941,https://www.bbc.co.uk/news/business-60623941?a...,One of the world's biggest fertiliser firms sa...
3,Manchester Arena bombing: Saffie Roussos's par...,"Mon, 07 Mar 2022 00:05:40 GMT",https://www.bbc.co.uk/news/uk-60579079,https://www.bbc.co.uk/news/uk-60579079?at_medi...,The parents of the Manchester Arena bombing's ...
4,Ukraine conflict: Oil price soars to highest l...,"Mon, 07 Mar 2022 08:15:53 GMT",https://www.bbc.co.uk/news/business-60642786,https://www.bbc.co.uk/news/business-60642786?a...,Consumers are feeling the impact of higher ene...
...,...,...,...,...,...
13404,Wolves 3-0 Liverpool: Twelve minutes of misery...,"Sat, 04 Feb 2023 18:50:55 GMT",https://www.bbc.co.uk/sport/football/64525812,https://www.bbc.co.uk/sport/football/64525812?...,A nightmare opening 12 minutes against Wolves ...
13405,Davis Cup 2023: Great Britain reach Finals as ...,"Sat, 04 Feb 2023 23:50:46 GMT",https://www.bbc.co.uk/sport/tennis/64525522,https://www.bbc.co.uk/sport/tennis/64525522?at...,Cameron Norrie confirms Great Britain's place ...
13406,Duhan van der Merwe scores sensational Six Nat...,"Sat, 04 Feb 2023 18:59:18 GMT",https://www.bbc.co.uk/sport/av/rugby-union/645...,https://www.bbc.co.uk/sport/av/rugby-union/645...,Watch Scotland winger Duhan van der Merwe scor...
13407,Six Nations highlights: England 23-29 Scotland,"Sat, 04 Feb 2023 19:08:41 GMT",https://www.bbc.co.uk/sport/av/rugby-union/644...,https://www.bbc.co.uk/sport/av/rugby-union/644...,Watch highlights as Duhan van der Merwe's late...
13408,Six Nations 2023: Wales 10-34 Ireland - Warren...,"Sat, 04 Feb 2023 16:11:04 GMT",https://www.bbc.co.uk/sport/rugby-union/64519964,https://www.bbc.co.uk/sport/rugby-union/645199...,Warren Gatland's return is spoiled by Ireland ...

In [4]:
data.drop(['title', 'pubDate', 'guid', 'link'], axis=1, inplace=True)

In [5]:
data

                                             description
0      The Ukrainian president says the country will ...
1      Jeremy Bowen was on the frontline in Irpin, as...
2      One of the world's biggest fertiliser firms sa...
3      The parents of the Manchester Arena bombing's ...
4      Consumers are feeling the impact of higher ene...
...                                                  ...
13404  A nightmare opening 12 minutes against Wolves ...
13405  Cameron Norrie confirms Great Britain's place ...
13406  Watch Scotland winger Duhan van der Merwe scor...
13407  Watch highlights as Duhan van der Merwe's late...
13408  Warren Gatland's return is spoiled by Ireland ...

[13409 rows x 1 columns]

In [5]:
!pip install transformers

Collecting transformers
  Downloading transformers-4.51.3-py3-none-any.whl.metadata (38 kB)
Collecting filelock (from transformers)
  Downloading filelock-3.18.0-py3-none-any.whl.metadata (2.9 kB)
Collecting huggingface-hub<1.0,>=0.30.0 (from transformers)
  Downloading huggingface_hub-0.30.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from transformers) (2.2.2)
Requirement already satisfied: packaging>=20.0 in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from transformers) (24.2)
Collecting pyyaml>=5.1 (from transformers)
  Downloading PyYAML-6.0.2-cp312-cp312-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: regex!=2019.12.17 in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from transformers) (2.32.3)
Collecting tokenizers<0.22,>=0.21 (from transformers)
  Downloading tokenizers-0.21.1-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
Collecting safetensors>=0.4.3 (from transformers)
  Downloading safetensors-0.5.3-cp38-abi3-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: tqdm>=4.27 in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from transformers) (4.67.1)
Collecting fsspec>=2023.5.0 (from huggingface-hub<1.0,>=0.30.0->transformers)
  Downloading fsspec-2025.3.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.12.2)
Requirement already satisfied: colorama in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from requests->transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from requests->transformers) (2025.1.31)
Downloading transformers-4.51.3-py3-none-any.whl (10.4 MB)
   ---------------------------------------- 0.0/10.4 MB ? eta -:--:--
   -- ------------------------------------- 0.5/10.4 MB 4.2 MB/s eta 0:00:03
   ------ --------------------------------- 1.6/10.4 MB 4.9 MB/s eta 0:00:02
   --------- ------------------------------ 2.4/10.4 MB 4.5 MB/s eta 0:00:02
   -------------- ------------------------- 3.7/10.4 MB 5.0 MB/s eta 0:00:02
   ------------------- -------------------- 5.0/10.4 MB 5.4 MB/s eta 0:00:02
   ------------------------ --------------- 6.3/10.4 MB 5.6 MB/s eta 0:00:01
   ---------------------------- ----------- 7.3/10.4 MB 5.5 MB/s eta 0:00:01
   -------------------------------- ------- 8.4/10.4 MB 5.4 MB/s eta 0:00:01
   ------------------------------------- -- 9.7/10.4 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------- 10.4/10.4 MB 5.2 MB/s eta 0:00:00
Downloading huggingface_hub-0.30.2-py3-none-any.whl (481 kB)
Downloading PyYAML-6.0.2-cp312-cp312-win_amd64.whl (156 kB)
Downloading safetensors-0.5.3-cp38-abi3-win_amd64.whl (308 kB)
Downloading tokenizers-0.21.1-cp39-abi3-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ----------------- ---------------------- 1.0/2.4 MB 5.6 MB/s eta 0:00:01
   -------------------------------------- - 2.4/2.4 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 5.2 MB/s eta 0:00:00
Downloading filelock-3.18.0-py3-none-any.whl (16 kB)
Downloading fsspec-2025.3.2-py3-none-any.whl (194 kB)
Installing collected packages: safetensors, pyyaml, fsspec, filelock, huggingface-hub, tokenizers, transformers
Successfully installed filelock-3.18.0 fsspec-2025.3.2 huggingface-hub-0.30.2 pyyaml-6.0.2 safetensors-0.5.3 tokenizers-0.21.1 transformers-4.51.3

In [6]:
!pip install torch

Collecting torch
  Downloading torch-2.7.0-cp312-cp312-win_amd64.whl.metadata (29 kB)
Requirement already satisfied: filelock in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from torch) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from torch) (4.12.2)
Collecting sympy>=1.13.3 (from torch)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch)
  Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: jinja2 in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from torch) (3.1.5)
Requirement already satisfied: fsspec in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from torch) (2025.3.2)
Requirement already satisfied: setuptools in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from torch) (72.1.0)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\inder\appdata\local\miniconda3\envs\nlp\lib\site-packages (from jinja2->torch) (3.0.2)
Downloading torch-2.7.0-cp312-cp312-win_amd64.whl (212.5 MB)
   ---------------------------------------- 0.0/212.5 MB ? eta -:--:--
   ---------------------------------------- 2.1/212.5 MB 11.8 MB/s eta 0:00:18
    --------------------------------------- 4.5/212.5 MB 11.2 MB/s eta 0:00:19
   - -------------------------------------- 6.3/212.5 MB 10.7 MB/s eta 0:00:20
   - -------------------------------------- 7.3/212.5 MB 9.3 MB/s eta 0:00:23
   - -------------------------------------- 8.1/212.5 MB 8.1 MB/s eta 0:00:26
   - -------------------------------------- 8.7/212.5 MB 7.2 MB/s eta 0:00:29
   - -------------------------------------- 9.4/212.5 MB 6.3 MB/s eta 0:00:33
   - -------------------------------------- 10.5/212.5 MB 6.2 MB/s eta 0:00:33
   -- ------------------------------------- 11.0/212.5 MB 5.7 MB/s eta 0:00:36
   -- ------------------------------------- 12.1/212.5 MB 5.6 MB/s eta 0:00:36
   -- ------------------------------------- 13.6/212.5 MB 5.7 MB/s eta 0:00:35
   -- ------------------------------------- 14.9/212.5 MB 5.8 MB/s eta 0:00:35
   --- ------------------------------------ 16.5/212.5 MB 5.9 MB/s eta 0:00:34
   --- ------------------------------------ 18.1/212.5 MB 6.0 MB/s eta 0:00:33
   --- ------------------------------------ 19.7/212.5 MB 6.1 MB/s eta 0:00:32
   --- ------------------------------------ 21.0/212.5 MB 6.1 MB/s eta 0:00:32
   ---- ----------------------------------- 23.1/212.5 MB 6.3 MB/s eta 0:00:30
   ---- ----------------------------------- 24.6/212.5 MB 6.4 MB/s eta 0:00:30
   ----- ---------------------------------- 27.3/212.5 MB 6.6 MB/s eta 0:00:28
   ----- ---------------------------------- 29.4/212.5 MB 6.8 MB/s eta 0:00:27
   ----- ---------------------------------- 30.7/212.5 MB 6.8 MB/s eta 0:00:27
   ------ --------------------------------- 33.3/212.5 MB 7.0 MB/s eta 0:00:26
   ------ --------------------------------- 35.9/212.5 MB 7.3 MB/s eta 0:00:25
   ------- -------------------------------- 37.7/212.5 MB 7.3 MB/s eta 0:00:24
   ------- -------------------------------- 39.6/212.5 MB 7.4 MB/s eta 0:00:24
   ------- -------------------------------- 41.2/212.5 MB 7.4 MB/s eta 0:00:24
   -------- ------------------------------- 42.7/212.5 MB 7.4 MB/s eta 0:00:24
   -------- ------------------------------- 44.8/212.5 MB 7.4 MB/s eta 0:00:23
   -------- ------------------------------- 47.2/212.5 MB 7.6 MB/s eta 0:00:22
   --------- ------------------------------ 49.3/212.5 MB 7.7 MB/s eta 0:00:22
   --------- ------------------------------ 50.1/212.5 MB 7.6 MB/s eta 0:00:22
   --------- ------------------------------ 52.4/212.5 MB 7.6 MB/s eta 0:00:21
   ---------- ----------------------------- 54.3/212.5 MB 7.6 MB/s eta 0:00:21
   ---------- ----------------------------- 54.8/212.5 MB 7.7 MB/s eta 0:00:21
   ---------- ----------------------------- 54.8/212.5 MB 7.7 MB/s eta 0:00:21
   ---------- ----------------------------- 54.8/212.5 MB 7.7 MB/s eta 0:00:21
   ---------- ----------------------------- 54.8/212.5 MB 7.7 MB/s eta 0:00:21
   ---------- ----------------------------- 54.8/212.5 MB 7.7 MB/s eta 0:00:21
   ---------- ----------------------------- 54.8/212.5 MB 7.7 MB/s eta 0:00:21
   ---------- ----------------------------- 54.8/212.5 MB 7.7 MB/s eta 0:00:21
   ---------- ----------------------------- 55.3/212.5 MB 6.3 MB/s eta 0:00:26
   ---------- ----------------------------- 57.4/212.5 MB 6.4 MB/s eta 0:00:25
   ----------- ---------------------------- 60.8/212.5 MB 6.6 MB/s eta 0:00:24
   ------------ --------------------------- 64.2/212.5 MB 6.8 MB/s eta 0:00:22
   ------------ --------------------------- 68.4/212.5 MB 7.1 MB/s eta 0:00:21
   ------------- -------------------------- 70.8/212.5 MB 7.2 MB/s eta 0:00:20
   ------------- -------------------------- 73.1/212.5 MB 7.3 MB/s eta 0:00:20
   -------------- ------------------------- 75.2/212.5 MB 7.3 MB/s eta 0:00:19
   -------------- ------------------------- 77.6/212.5 MB 7.4 MB/s eta 0:00:19
   --------------- ------------------------ 79.7/212.5 MB 7.5 MB/s eta 0:00:18
   --------------- ------------------------ 82.6/212.5 MB 7.6 MB/s eta 0:00:18
   ---------------- ----------------------- 85.5/212.5 MB 7.7 MB/s eta 0:00:17
   ---------------- ----------------------- 88.6/212.5 MB 7.8 MB/s eta 0:00:16
   ----------------- ---------------------- 91.5/212.5 MB 7.9 MB/s eta 0:00:16
   ----------------- ---------------------- 94.6/212.5 MB 8.1 MB/s eta 0:00:15
   ------------------ --------------------- 96.5/212.5 MB 8.1 MB/s eta 0:00:15
   ------------------ --------------------- 98.8/212.5 MB 8.1 MB/s eta 0:00:14
   ------------------ --------------------- 99.6/212.5 MB 8.1 MB/s eta 0:00:14
   ------------------ --------------------- 99.6/212.5 MB 8.1 MB/s eta 0:00:14
   ------------------ --------------------- 99.6/212.5 MB 8.1 MB/s eta 0:00:14
   ------------------ --------------------- 99.6/212.5 MB 8.1 MB/s eta 0:00:14
   ------------------ --------------------- 99.6/212.5 MB 8.1 MB/s eta 0:00:14
   ------------------ --------------------- 99.6/212.5 MB 8.1 MB/s eta 0:00:14
   ------------------ --------------------- 99.6/212.5 MB 8.1 MB/s eta 0:00:14
   ------------------ --------------------- 99.6/212.5 MB 8.1 MB/s eta 0:00:14
   ------------------ --------------------- 100.1/212.5 MB 7.1 MB/s eta 0:00:16
   ------------------- -------------------- 103.3/212.5 MB 7.2 MB/s eta 0:00:16
   -------------------- ------------------- 107.2/212.5 MB 7.4 MB/s eta 0:00:15
   --------------------- ------------------ 111.9/212.5 MB 7.6 MB/s eta 0:00:14
   --------------------- ------------------ 115.9/212.5 MB 7.8 MB/s eta 0:00:13
   ---------------------- ----------------- 121.6/212.5 MB 8.0 MB/s eta 0:00:12
   ----------------------- ---------------- 125.0/212.5 MB 8.1 MB/s eta 0:00:11
   ------------------------ --------------- 127.9/212.5 MB 8.2 MB/s eta 0:00:11
   ------------------------ --------------- 130.0/212.5 MB 8.2 MB/s eta 0:00:10
   ------------------------ --------------- 132.1/212.5 MB 8.3 MB/s eta 0:00:10
   ------------------------- -------------- 134.2/212.5 MB 8.3 MB/s eta 0:00:10
   ------------------------- -------------- 136.3/212.5 MB 8.3 MB/s eta 0:00:10
   -------------------------- ------------- 138.1/212.5 MB 8.3 MB/s eta 0:00:09
   -------------------------- ------------- 140.2/212.5 MB 8.3 MB/s eta 0:00:09
   -------------------------- ------------- 142.6/212.5 MB 8.4 MB/s eta 0:00:09
   --------------------------- ------------ 144.4/212.5 MB 8.4 MB/s eta 0:00:09
   --------------------------- ------------ 146.5/212.5 MB 8.4 MB/s eta 0:00:08
   --------------------------- ------------ 147.6/212.5 MB 8.4 MB/s eta 0:00:08
   ---------------------------- ----------- 149.2/212.5 MB 8.4 MB/s eta 0:00:08
   ---------------------------- ----------- 150.7/212.5 MB 8.3 MB/s eta 0:00:08
   ---------------------------- ----------- 152.3/212.5 MB 8.3 MB/s eta 0:00:08
   ----------------------------- ---------- 154.1/212.5 MB 8.3 MB/s eta 0:00:08
   ----------------------------- ---------- 155.5/212.5 MB 8.3 MB/s eta 0:00:07
   ----------------------------- ---------- 156.5/212.5 MB 8.3 MB/s eta 0:00:07
   ----------------------------- ---------- 157.3/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 157.8/212.5 MB 8.2 MB/s eta 0:00:07
   ----------------------------- ---------- 158.1/212.5 MB 5.7 MB/s eta 0:00:10
   ----------------------------- ---------- 158.3/212.5 MB 5.7 MB/s eta 0:00:10
   ----------------------------- ---------- 158.9/212.5 MB 5.7 MB/s eta 0:00:10
   ----------------------------- ---------- 159.1/212.5 MB 5.6 MB/s eta 0:00:10
   ------------------------------ --------- 159.4/212.5 MB 5.6 MB/s eta 0:00:10
   ------------------------------ --------- 159.9/212.5 MB 5.6 MB/s eta 0:00:10
   ------------------------------ --------- 160.2/212.5 MB 5.5 MB/s eta 0:00:10
   ------------------------------ --------- 160.4/212.5 MB 5.5 MB/s eta 0:00:10
   ------------------------------ --------- 160.7/212.5 MB 5.5 MB/s eta 0:00:10
   ------------------------------ --------- 161.2/212.5 MB 5.5 MB/s eta 0:00:10
   ------------------------------ --------- 161.7/212.5 MB 5.4 MB/s eta 0:00:10
   ------------------------------ --------- 162.3/212.5 MB 5.4 MB/s eta 0:00:10
   ------------------------------ --------- 162.8/212.5 MB 5.4 MB/s eta 0:00:10
   ------------------------------ --------- 163.1/212.5 MB 5.3 MB/s eta 0:00:10
   ------------------------------ --------- 163.1/212.5 MB 5.3 MB/s eta 0:00:10
   ------------------------------ --------- 163.3/212.5 MB 5.2 MB/s eta 0:00:10
   ------------------------------ --------- 163.3/212.5 MB 5.2 MB/s eta 0:00:10
   ------------------------------ --------- 163.3/212.5 MB 5.2 MB/s eta 0:00:10
   ------------------------------ --------- 163.3/212.5 MB 5.2 MB/s eta 0:00:10
   ------------------------------ --------- 163.6/212.5 MB 5.1 MB/s eta 0:00:10
   ------------------------------ --------- 163.8/212.5 MB 5.1 MB/s eta 0:00:10
   ------------------------------ --------- 164.4/212.5 MB 5.1 MB/s eta 0:00:10
   ------------------------------- -------- 164.9/212.5 MB 5.1 MB/s eta 0:00:10
   ------------------------------- -------- 165.9/212.5 MB 5.1 MB/s eta 0:00:10
   ------------------------------- -------- 167.0/212.5 MB 5.1 MB/s eta 0:00:09
   ------------------------------- -------- 168.0/212.5 MB 5.0 MB/s eta 0:00:09
   ------------------------------- -------- 169.9/212.5 MB 5.0 MB/s eta 0:00:09
   -------------------------------- ------- 171.2/212.5 MB 5.0 MB/s eta 0:00:09
   -------------------------------- ------- 173.0/212.5 MB 5.0 MB/s eta 0:00:08
   -------------------------------- ------- 174.9/212.5 MB 5.0 MB/s eta 0:00:08
   --------------------------------- ------ 176.7/212.5 MB 5.0 MB/s eta 0:00:08
   --------------------------------- ------ 178.0/212.5 MB 5.0 MB/s eta 0:00:07
   --------------------------------- ------ 178.5/212.5 MB 5.0 MB/s eta 0:00:07
   --------------------------------- ------ 179.3/212.5 MB 5.0 MB/s eta 0:00:07
   --------------------------------- ------ 179.3/212.5 MB 5.0 MB/s eta 0:00:07
   --------------------------------- ------ 180.4/212.5 MB 4.8 MB/s eta 0:00:07
   ---------------------------------- ----- 181.4/212.5 MB 4.8 MB/s eta 0:00:07
   ---------------------------------- ----- 183.0/212.5 MB 4.8 MB/s eta 0:00:07
   ---------------------------------- ----- 185.1/212.5 MB 4.8 MB/s eta 0:00:06
   ----------------------------------- ---- 187.4/212.5 MB 4.8 MB/s eta 0:00:06
   ----------------------------------- ---- 189.3/212.5 MB 4.8 MB/s eta 0:00:05
   ----------------------------------- ---- 190.8/212.5 MB 4.8 MB/s eta 0:00:05
   ------------------------------------ --- 192.2/212.5 MB 4.8 MB/s eta 0:00:05
   ------------------------------------ --- 193.5/212.5 MB 4.8 MB/s eta 0:00:04
   ------------------------------------ --- 195.0/212.5 MB 4.8 MB/s eta 0:00:04
   ------------------------------------ --- 196.3/212.5 MB 4.8 MB/s eta 0:00:04
   ------------------------------------- -- 198.4/212.5 MB 5.0 MB/s eta 0:00:03
   ------------------------------------- -- 200.0/212.5 MB 5.1 MB/s eta 0:00:03
   ------------------------------------- -- 201.9/212.5 MB 5.1 MB/s eta 0:00:03
   -------------------------------------- - 203.4/212.5 MB 5.1 MB/s eta 0:00:02
   -------------------------------------- - 204.7/212.5 MB 5.1 MB/s eta 0:00:02
   -------------------------------------- - 206.6/212.5 MB 5.1 MB/s eta 0:00:02
   ---------------------------------------  208.1/212.5 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------  209.7/212.5 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------  210.5/212.5 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------  212.1/212.5 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------  212.3/212.5 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------  212.3/212.5 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------  212.3/212.5 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------- 212.5/212.5 MB 4.7 MB/s eta 0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   ----------- ---------------------------- 1.8/6.3 MB 10.1 MB/s eta 0:00:01
   ------------------------ --------------- 3.9/6.3 MB 10.2 MB/s eta 0:00:01
   -------------------------------------- - 6.0/6.3 MB 10.0 MB/s eta 0:00:01
   ---------------------------------------- 6.3/6.3 MB 9.4 MB/s eta 0:00:00
Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------------ --------------------- 0.8/1.7 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 4.5 MB/s eta 0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
   ---------------------------------------- 536.2/536.2 kB 4.4 MB/s eta 0:00:00
Installing collected packages: mpmath, sympy, networkx, torch
Successfully installed mpmath-1.3.0 networkx-3.4.2 sympy-1.14.0 torch-2.7.0

In [7]:
import torch
from transformers import GPT2Tokenizer, GPT2LMHeadModel

c:\Users\inder\AppData\Local\miniconda3\envs\NLP\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [8]:
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2LMHeadModel.from_pretrained('gpt2')
model.eval()

c:\Users\inder\AppData\Local\miniconda3\envs\NLP\Lib\site-packages\huggingface_hub\file_download.py:144: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\inder\.cache\huggingface\hub\models--gpt2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [ ]:
# Iterate over each row in the dataframe
for i, row in data.iterrows():
    prompt = row["description"]  # replace "column_name_for_prompt" with the actual name of the column in your dataframe
    input_ids = torch.tensor(tokenizer.encode(prompt)).unsqueeze(0)  # encode the prompt
    output = model.generate(input_ids=input_ids, max_length=100, do_sample=True)  # generate text
    generated_text = tokenizer.decode(output[0], skip_special_tokens=True)  # decode the generated text
    print("Generated text for input: ", prompt)
    print(generated_text)

In [ ]:
# Create a DataFrame from the list
df = pd.DataFrame(generated_text, columns=["generated_text"])

In [ ]:
generated_text_new.to_csv("generated_text.csv", index=False)